name: Sync multiple branches
on:
  push:
    branches:
      - master
jobs:
  merge-from-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> deploy
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: deploy
          github_token: ${{ github.token }}
