name: Build client App and create deploy branch
on: push
jobs:
  prepare-deploy-branch:
    name: Prepare deploy branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
      - name: Configure git
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}
      - name: Merge master onto deploy
        run: git merge origin/master
      - name: Remove previous client application build
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./server/public
  build-client-application:
    name: Prepare deploy branch
    runs-on: ubuntu-latest
    needs: prepare-deploy-branch
    steps:
      - name: Install Dependencies for client application.
        working-directory: ./client
        run: npm install
      - name: Build client application.
        working-directory: ./client
        run: npm run build
      - name: Remove .github folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.github
      - name: Remove client folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./client
      - name: Remove .idea folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.idea
      - name: Remove .gitignore
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.gitignore
      - name: Push to deploy branch
        run: |
          git add -A .
          git commit -m "Created deploy branch by continuous-integration workflow"
          git push origin deploy
