name: Build client App and create deploy branch
on: push
jobs:
  build:
    name: Build client application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
      - name: Create deploy branch
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}
          git push origin --delete deploy
          git checkout -B deploy
          git merge master
      - name: Remove .workflows folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: /.workflows
      - name: Remove client folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: /client
      - name: Remove .idea folder
        uses: JesseTG/rm@v1.0.2
        with:
          path: /.idea
      - name: Remove .gitignore
        uses: JesseTG/rm@v1.0.2
        with:
          path: /.gitignore
      - name: Push deploy branch
        run: |
          git add -A .
          git commit -m "Created deploy branch"
          git push origin deploy
