name: Build client App and create deploy branch
on: push
jobs:
  build:
    name: Build client application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
